TheStation/urls.py
import django
from django.conf.urls import patterns, include, url
from django.contrib import admin
from station import views
from django.conf import settings

urlpatterns = [
    # Examples:
    # url(r'^$', 'TheStation.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^current_and_next_song$', views.current_and_next_song),
    url(r'^$', views.player, name="home"),
    url(r'^play$', views.player, {'autoplay': True}, name="autoplay"),
    url(r'^get_artist_donate_address$', views.get_artist_donate_address, name="get_artist_donate_address"),
    url(r'^upload$', views.upload, name="upload"),
    url(r'^stats$', views.station_stats, name='station_stats'),
]

if settings.DEBUG:
    urlpatterns.append(
        url(r'^mp3/(?P<path>.*)$', django.views.static.serve, {'document_root': settings.MEDIA_ROOT}),
    )

station/models.py
import datetime
import random
import requests
import urllib2

from moneywagon import get_address_balance, get_current_price

import pytz
from django.db import models
from django.core.files import File
from django.core.files.temp import NamedTemporaryFile

from pybitcoin import BitcoinPrivateKey
from django.conf import settings
from django.core.cache import caches

# seconds to schedule between songs
SONG_PADDING = 2

class Feature(models.Model):
    song = models.ForeignKey('station.Song', related_name='featured_songs')
    artist = models.ForeignKey('station.Artist', related_name='featuring_artists')
    ratio = models.FloatField(blank=True, null=True)

    def __unicode__(self):
        return "feat. %s" % self.artist.name

class Song(models.Model):
    artist = models.ForeignKey('station.Artist', related_name='songs')
    title = models.TextField()
    duration = models.DurationField()
    explicit = models.BooleanField(default=False)
    collection = models.TextField(blank=True)
    genre = models.TextField(blank=True)
    subgenre= models.TextField(blank=True)
    recorded_date = models.DateField()
    featuring = models.ManyToManyField('station.Artist', through='station.Feature', blank=True)
    retired = models.BooleanField(default=False)
    mp3filesize = models.IntegerField(default=None, null=True, blank=True)

    mp3 = models.FileField(null=True, blank=True)

    image = models.ImageField(blank=True)

    class Meta:
        unique_together = (("title", "artist"),)

    def __unicode__(self):
        return "%s - %s%s" % (self.artist.name, self.title, self.feat())

    @classmethod
    def eligible_for_broadcast(cls):
        """
        Returns a queryset of all songs that have mp3, cover and are no retired.
        """
        return cls.objects.exclude(mp3='').exclude(image='').exclude(retired=True)

    def fetch_from_lastfm(self):
        url = "http://ws.audioscrobbler.com/2.0/?method=track.getInfo&api_key=%s&artist=%s&track=%s&format=json" % (
            settings.LASTFM_KEY, self.artist.name, "%s %s" % (self.title, self.feat)
        )
        return requests.get(url).json()

    @property
    def year(self):
        return self.recorded_date.strftime("%Y")

    def fetch_img(self):
        response = self.fetch_from_lastfm()
        imgsrc = response['track']['album']['image'][3]['#text']
        img_temp = NamedTemporaryFile(delete=True)
        img_temp.write(urllib2.urlopen(imgsrc).read())
        img_temp.flush()
        self.image = File(img_temp)
        self.save()

    def feat(self):
        """
        Make the little "feat" tag to put at the end of the title of the song
        has featuring artists. This function handles putting the commas and
        amperstand depending on how many features there are.
        """
        featuring = list(self.featuring.all())

        if not featuring:
            return ""

        if len(featuring) == 1:
            return " (feat. %s)" % featuring[0].name
        elif len(featuring) == 2:
            return " (feat. %s & %s)" % tuple([x.name for x in featuring])

        last_two = "%s & %s" % tuple([x.name for x in featuring[-2:]])
        return " (feat. %s, %s)" % (
            " ,".join([x.name for x in featuring[:-2]]), last_two
        )

    def estimate_bitrate_kbps(self):
        """
        Calculate approximate bitrate based on filesize and duration.
        Returns a number that is kilobits per second.
        """
        return (((self.mp3filesize or 0) / 1024) * 8) / self.duration.total_seconds()

    def get_tips(self):
        """
        Always returns a list of dicts, each dict containing all the data needed
        to make the microtip meta tags, or microtip audio tag.
        """
        if self.featuring.exists():
            feature_tips = []
            all_features = list(Feature.objects.filter(song=self))
            share = 0.5 / len(all_features)
            for feature in all_features:
                feature_tips.append({
                    'recipient': feature.artist.name,
                    'ratio': feature.ratio or share,
                    'address': feature.artist.address,
                })
            return feature_tips + [{
                'recipient': self.artist.name,
                'ratio': 0.5,
                'address': self.artist.address,
            }]

        return [{
            'recipient': self.artist.name,
            'ratio': 1.0,
            'address': self.artist.address,
        }]

    @property
    def last_played(self):
        """
        When the last time his song was played.
        """
        return self.stationplay_set.latest('ordinal').start_time

    @property
    def last_played_ago(self):
        return datetime.datetime.now(pytz.utc) - self.last_played

    def is_valid_next(self, last_song):
        """
        Is this song eligible to be the next song in the station?
        Determine this by comparing it with the
        """
        if not self.image:
            return False

        if self.genre and self.genre == last_song.genre:
            return False

        if self.collection and last_song.collection == self.collection:
            return False

        if self.year[:3] == last_song.year[:3]:
            # same decade
            return False

        title_repeat = int(Song.objects.count() / 2)
        artist_repeat = int(Artist.objects.count() / 3)

        last_artists = StationPlay.objects.order_by('-ordinal')[:artist_repeat]
        plays_last_title = StationPlay.objects.order_by('-ordinal')[:title_repeat]

        if self.artist in [x.song.artist for x in last_artists]:
            return False
        if self.title in [x.song.title for x in plays_last_title]:
            return False
        return True

def migrate_mp3ilesize():
    for s in Song.objects.all():
        s.mp3filesize = s.mp3.size
        s.save()
        print s.estimate_bitrate_kbps()

class Artist(models.Model):
    name = models.TextField(unique=True)
    private_key_hex = models.CharField(max_length=64, blank=True)
    address = models.CharField(max_length=50, blank=True)

    def __unicode__(self):
        return self.name

    def get_tipped_value(self):
        """
        Check the blokchain to see how many tips have been collected.
        """
        if not self.address:
            return 0

        cache = caches['default']
        price = cache.get('btc-price')
        if not price:
            price, source = get_current_price('btc', 'usd')
            cache.set('btc-price', price)

        status_balance = cache.get(self.address)
        if not status_balance:
            balance = get_address_balance('btc', self.address)
            cache.set(self.address, ['OK', balance])
        else:
            status, balance = status_balance

        return balance * price

    def is_verified(self):
        """
        Verified means the artist itself has control over the private key,
        therefore, in this database, the private key is not known.
        """
        return not bool(self.private_key_hex)

    def generate_address(self, force=False):
        if self.address and not force:
            return

        if not settings.ARTIST_DONATE_ADDRESS_SOURCE:
            # No donate address has been given in settings
            # this means we generate a unique one and store the private key
            # along with it. It is the responsibility of the maintainer
            # if this installation to make sure the private key is distributed
            # to the artist.

            priv = BitcoinPrivateKey()
            self.private_key_hex = priv.to_hex()
            self.address = priv.public_key().address()
            self.save()
        else:
            # point to another installation of TheStation to get the correct
            # donate address.
            url = (
                "http://" + settings.ARTIST_DONATE_ADDRESS_SOURCE +
                "/get_artist_donate_address" +
                "?artist=%s" % self.name
            )
            self.address = requests.get(url).json()['donate_address']
            self.save()

        return self.address

    def private_key_wif(self):
        return BitcoinPrivateKey(self.private_key_hex).to_wif()

class StationPlay(models.Model):
    ordinal = models.AutoField(primary_key=True)
    song = models.ForeignKey('station.Song')
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()

    def __unicode__(self):
        return "%s - %s - %s" % (self.start_time, self.song, self.end_time)

    @classmethod
    def average_bandwidth_kbps(cls):
        """
        Returns the average kilobits per second for all songs in the library.
        """
        data = [x.estimate_bitrate_kbps() for x in Song.eligible_for_broadcast()]
        if not len(data):
            return 0
        return sum(data) / len(data)

    @classmethod
    def average_duration_minutes(cls):
        """
        Calculate the average number of minutes each song is in the song library.
        """
        data = [x.duration.total_seconds() for x in Song.eligible_for_broadcast()]
        if not len(data):
            return 0
        return sum(data) / len(data) / 60

    @classmethod
    def average_bytes_per_song(cls):
        """
        The Average bytes of bandwidth used per song.
        """
        data = [x.mp3filesize for x in Song.eligible_for_broadcast()]
        if not len(data):
            return 0
        return int(sum(data) / len(data))

    @classmethod
    def average_bytes_per_minute(cls):
        """
        The Average bytes of bandwidth used per song.
        """
        bytes_per_song = cls.average_bytes_per_song()
        minutes_per_song = cls.average_duration_minutes()
        return int(bytes_per_song / minutes_per_song)

    @classmethod
    def cost_per_song_per_user_usd(cls):
        gb_per_song = cls.average_bytes_per_song() / 1024.0 / 1024.0 / 1024.0

station/forms.py
import urllib2

from django import forms
from .models import Song, Artist
from django.core.files import File
from django.core.files.temp import NamedTemporaryFile

class SongFormImageURL(forms.ModelForm):
    image_url = forms.URLField(required=False)

    def clean(self, *args, **kwargs):
        all_data = self.cleaned_data
        url = all_data['image_url']
        image = all_data['image']

        if not image and url:
            img_temp = NamedTemporaryFile(delete=True)
            img_temp.write(urllib2.urlopen(url).read())
            img_temp.flush()
            all_data['image'] = File(img_temp)

        return all_data

    class Meta:
        model = Song
        exclude = ('featuring', )
        widgets = {
            'collection': forms.TextInput,
            'genre': forms.TextInput,
            'subgenre': forms.TextInput,
            'title': forms.TextInput,
            'mp3filesize': forms.HiddenInput
        }

class UploadSongForm(SongFormImageURL):
    artist = forms.CharField(widget=forms.TextInput)

    def clean_artist(self):
        artist, c = Artist.objects.get_or_create(name=self.cleaned_data['artist'])
        return artist

station/views.py
import datetime
import pytz
import json

from django.shortcuts import render
from django.http import JsonResponse, HttpResponseRedirect, HttpResponseForbidden
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.conf import settings

from .models import StationPlay, Artist, Song
from .forms import UploadSongForm

def get_current_and_next_play():
    now = datetime.datetime.now(pytz.utc)

    try:
        current_play = StationPlay.objects.get(start_time__lt=now, end_time__gt=now)
    except StationPlay.DoesNotExist:
        # no current_play == station went dead due to no listeners
        current_play, tries = StationPlay.generate_next(now)
    except StationPlay.MultipleObjectsReturned:
        # keep the first, delete the second duplicate
        sp = StationPlay.objects.filter(start_time__lt=now, end_time__gt=now)
        current_play = sp[0]
        [x.delete() for x in sp[1:]]

    try:
        next_play = StationPlay.objects.get(start_time__gt=now)
    except StationPlay.DoesNotExist:
        # first hit after a new generated song, generate the next song.
        next_play, tries = StationPlay.generate_next(current_play.end_time)
        print "Generated new track, tried this many times:", tries

    next_fetch = next_play.start_time + (next_play.song.duration / 2)

    return current_play, next_play, next_fetch

def current_and_next_song(request):
    """
    View to handle the API call for getting the next and currently playing
    song.
    """
    current_play, next_play, next_fetch = get_current_and_next_play()
    return JsonResponse({
        'current_song': current_play.as_dict(),
        'next_song': next_play.as_dict(),
        'next_fetch': next_fetch,
    })

def player(request, autoplay=False):
    """
    This view handles making the main audio player page. Aka the home page.
    """
    current_play, next_play, next_fetch = get_current_and_next_play()
    return render(request, "home.html", {
        'current_play': current_play.as_dict(),
        'next_play': next_play.as_dict(),
        'autoplay': autoplay,
        'TITLE': settings.TITLE,
        'BANDWIDTH_FUND_ADDRESS': settings.BANDWIDTH_FUND_ADDRESS,
        'next_fetch': next_fetch,
        'next_play_json': json.dumps(next_play.as_dict()), # django should have a built-in json template tag
        'current_play_tips_json': json.dumps(current_play.as_dict()['tips']),
    })

@login_required
def upload(request):
    """
    A very basic MP3 uploader form.
    """
    form = UploadSongForm()
    if request.POST:
        form = UploadSongForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            url = reverse("upload")
            return HttpResponseRedirect(url)

    LASTFM_KEY = settings.LASTFM_KEY
    return render(request, "upload.html", locals())

def get_artist_donate_address(request):
    """
    Most likely this view is being called by another installation of TheStation
    We return the donate address of the artist passed in.
    """
    if not settings.SERVE_ADDRESSES:
        raise HttpResponseForbidden("Not enabled")

    artist_name = request.GET['artist']
    try:
        artist = Artist.objects.get(name__iexact=artist_name)
    except Artist.DoesNotExist:
        artist = Artist.objects.create(name=artist_name)
        artist.generate_address()

    return JsonResponse({
        'donate_address': artist.address,
        'verified': artist.is_verified()
    })

def station_stats(request):
    return JsonResponse({
        'total_songs': Song.eligible_for_broadcast().count(),
        'average_bitrate_kbps': StationPlay.average_bandwidth_kbps(),
        'average_duration_minutes': StationPlay.average_duration_minutes(),
        'average_bytes_per_song': StationPlay.average_bytes_per_song(),
        'average_bytes_per_minute': StationPlay.average_bytes_per_minute(),
        'bandwidth_cost_per_song_usd': StationPlay.cost_per_song_per_user_usd(),
        'bandwidth_cost_per_minute_usd': StationPlay.cost_per_minute_per_user_usd()
    })

station/templates/base.html
<!DOCTYPE html>
<html>
<head></head>
<title>{{ TITLE|striptags }}</title>
<script src="{{ STATIC_URL }}admin/js/jquery.js"></script>
<body>
    {% block content %}{% endblock %}
    <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-501381-19', 'auto');
  ga('send', 'pageview');

</script>
</body>
</html>

station/templates/home.html
{% extends "base.html" %}

{% block content %}
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="microtip" content="Audio">
<meta name="microtip" content="{{ BANDWIDTH_FUND_ADDRESS }}" data-recipient="{{ TITLE|striptags }} Bandwidth Fund">
<link type="text/css" rel="stylesheet" href="{{ STATIC_URL }}station.css">

<div class="center">
    <audio id="player{% if current_play.id|divisibleby:"2" %}A{% else %}B{% endif%}" src='{{ current_play.url }}' preload='{% if autoplay %}auto{% else %}none{% endif %}'></audio>
    <audio id="player{% if next_play.id|divisibleby:"2" %}A{% else %}B{% endif%}" src='{{ next_play.url }}' preload='{% if autoplay %}auto{% else %}none{% endif %}'></audio>

    <h1>{{ TITLE|default:"The Station"|safe }}</h1>

    <div class="buttons">
        <button id="mute" style="display: none">Mute</button><button id="unmute" style="display: none">Un-mute</button>
        <button id="start2" style="display: none" onclick="window.location = '/play'">Restart</button>
        <button id="start">Start Listening</button>
        <button id="stop" style="display: none">Stop</button>
    </div>
    <br>
    <br>
    <div id="currently_playing" class="grayed pbg-0">
        <span class="status">Not Currently Streaming</span><br><br>
        <span class="mp3src">{{ current_play.url }}</span>
        <span class="tips">{{ current_play_tips_json }}</span>
        <img src='{{ current_play.img }}'><br>
        <span class='artist'>{{ current_play.artist }}</span>
        [<span class='year'>{{ current_play.year }}</span>]
        <span class='title'>{{ current_play.title }}</span><br>
        <span class='play-id'>{{ current_play.id }}</span>
        <span class='duration'>{{ current_play.duration }}</span>
        <span class='start_time'>{{ current_play.start_time }}</span>
        <progress value='0' max='1' style='width: 80%'></progress>
        <br>
    </div>
    <div id="next_song"></div>
    <div id="currently_playing_cache" style="display: none">
        <span class="status">Not Currently Streaming</span><br><br>
        <span class="mp3src">{{ next_play.url }}</span>
        <span class="tips">{{ next_play_tips_json }}</span>
        <img src='{{ next_play.img }}'><br>
        <span class='artist'>{{ next_play.artist }}</span>
        [<span class='year'>{{ next_play.year }}</span>]
        <span class='title'>{{ next_play.title }}</span><br>
        <span class='play-id'>{{ next_play.id }}</span>
        <span class='duration'>{{ next_play.duration }}</span>
        <span class='start_time'>{{ next_play.start_time }}</span>
        <progress value='0' max='1' style='width: 80%'></progress>
    </div>
    <br>
    <br>
    <div id="last_played_header" style="display:none">Play History:</div>
    <div id="last_played_container"></div>
    <small>
        Powered by <a href="http://github.com/priestc/TheStation">TheStation</a><br>
        Bandwidth and Artist monetization provided by <a href="http://autotip.io">Autotip</a><br>
        <a href="#" id='stats_link'>Station Stats</a> *
        <a href="#" id="about_link">About</a> *
        <a href="#" id="charts_link">Charts</a>
        <br>
        <div id="stats_display" style="display: none">
            <br>
            Total number of songs in library: <strong class="total_songs"></strong><br>
            Average bitrate of all songs: <strong class="average_bitrate_kbps"></strong> kbps<br>
            Average duration of each song: <strong class="average_duration_minutes"></strong> minutes<br>
            Average bandwidth used per song:<strong class="average_bytes_per_song"></strong> MB<br>
            Average bandwidth used per minute: <strong class="average_bytes_per_minute"></strong> MB<br>
            Bandwidth Cost per song per user: $<strong class="bandwidth_cost_per_song_usd"></strong> USD<br>
            Bandwidth Cost per minute per user: $<strong class="bandwidth_cost_per_minute_usd"></strong> USD<br>
        </div>
    </small>
</div>

<script type="text/javascript" src="{{ STATIC_URL }}admin/js/jquery.js"></script>

<script>
    var station_stats_url = '{% url "station_stats" %}';
</script>

<script src="{{ STATIC_URL}}station.js"></script>

<script>
    {% if autoplay %}
    // Automatically start the station because '/play' in url.
    $("#start").trigger('click');
    {% endif%}

    var fetch = new Date('{{ next_fetch.isoformat }}');
    var ms_to_fetch = miliseconds_from_now(fetch);
    console.log("HOME PAGE: scheduling first fetch for", fetch, "which is", ms_to_fetch / 1000, "seconds from now")
    setTimeout(fetch_next_track, ms_to_fetch);

    var next_start = new Date('{{ next_play.start_time }}');
    var ms_to_start = miliseconds_from_now(next_start);
    console.log("HOME PAGE: scheduling switch to {{ next_play.artist|safe }} {{ next_play.title|safe }} for", next_start, "in", ms_to_start / 1000, "seconds")
    setTimeout(switch_song, ms_to_start, {{ next_play_json|safe }});

    {% if autoplay %}
    setTimeout(make_random_background, (ms_to_start - 5000));
    {% endif %}

</script>

{% endblock %}

station/templates/upload.html
{% extends "base.html" %}

{% block content %}
    <style>
        input[type=text] {width: 20em}
    </style>
    <script src="{{ STATIC_URL }}musicmetadata.js"></script>
    <h1>Add new song to TheStation</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>
        <input type="submit">
    </form>
    <button id="get_img">Fetch Image</button>
    <div id="status"></div>
    <img id="img_preview">
    <script>
        function get_info_from_lastfm(artist_name, track_name, callback) {
            var key = "{{ LASTFM_KEY }}";

            if(key == '') {
                // No lastfm API key configured on the backend.
                return
            }

            var url = "http://ws.audioscrobbler.com/2.0/?method=track.getInfo&api_key=" + key +
            "&artist=" + artist_name + "&track=" + track_name + "&format=json";

            $.ajax({
                url: url,
                success: function(response) {
                    if(response.error) {
                        console.log("Last fm returned error:", response.message);
                        return
                    }
                    callback(response);
                },
                error: function() {
                    console.log("Can't get info from last.fm");
                }
            })
        }

        function to_ms(seconds) {
            // Convert seconds to MM:SS
            m = Math.floor(seconds / 60);
            s = seconds % 60;
            if(s < 10) {
                s = "0" + s;
            }
            return m + ":" + s;
        }

        function get_image(artist, title){
            get_info_from_lastfm(artist, title, function(info) {
                try {
                    var imgsrc = info.track.album.image[3]["#text"]; // 3 = large size
                    $("#id_image_url").val(imgsrc);
                    $("#img_preview").attr('src', imgsrc);
                    $("#status").text("");
                } catch (e) {
                    $("#id_image_url").val("");
                    $("#img_preview").attr('src', "");
                    console.log("Could not get info from last.fm", e);
                    var msg = "Could not get album art from last.fm for " + artist + " - " + title;
                    $("#status").text(msg);
                }
            });
        }


        $("#get_img").click(function() {
            var url = $("#id_image_url").val();
            if(url) {
                $("#img_preview").attr('src', url);
            } else {
                get_image($("#id_artist").val(), $("#id_title").val());
            }
        });

        $("#id_mp3").change(function(event) {
            var file = this.files[0];
            musicmetadata(file, {duration: true}, function(err, result) {
                $("#id_title").val(result.title);
                $("#id_artist").val(result.artist[0]);
                $("#id_collection").val(result.album);
                if(result.year) {
                    $("#id_recorded_date").val(result.year + "-01-01");
                }
                $("#id_duration").val(to_ms(result.duration));
                $("#id_image_url").val("Fetching...");
                $("#id_mp3filesize").val(file.size)

                get_image(result.artist[0], result.title);

            });
        });

    </script>
{% endblock %}